# Generated by Django 4.1.7 on 2023-04-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignupUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(max_length=25)),
                ('passwordHash', models.TextField(max_length=25)),
            ],
        ),
    ]
