# Generated by Django 4.1.7 on 2023-04-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupuser',
            name='email',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='signupuser',
            name='passwordHash',
            field=models.CharField(max_length=25),
        ),
    ]
